### ISSUE TITLE
Edit Togle issue

### ISSUE THREAD

**Issue by zlaasu** [SkyWriter/toggl#20]
Is it possible to edit Redmine logTime when someone edit the Togle entry?

**Comment by SkyWriter** [comment]
No, it's not, and that's a deliberate design choice.

Making it possible would raise a whole bunch of additional questions:

- What should happen if someone edits Redmine time entry?
- How the plugin should behave when Toggl item gets deleted? How far into the past of Toggl history should we look?
- How should Redtime time entries deletion be handled?
- ... etc

What's worse, having all of the questions answered and implementation in place doesn't really help much, since everyone's process is different and what's right for me isn't necessarily going to fit you.

So, instead the rules are very simple to grasp: any finished Toggl entry gets imported just once. That's it. No more business for a time entry at any side of the fence after that.

Having that said, I'm totally open to accepting pull requests and enabling users to select the need behaviour with a dropdown or something.
